# Base inference configuration template
# This will be used as a template for each checkpoint evaluation

# Base directories
base_data_dir: "/mnt/data/COMBINED"
output_path: "PLACEHOLDER_OUTPUT_PATH"  # Will be replaced by batch script
weight_path: "PLACEHOLDER_WEIGHT_PATH"  # Will be replaced by batch script

# Dataset configuration
SolO: "false"
Stereo: "false"

# Model configuration
model: "vit"  # Options: "vit", "hybrid", "vitpatch", "fusion"
wavelengths: [94, 131, 171, 193, 211, 304]  # AIA wavelengths in Angstroms

# MC Dropout configuration
mc:
  active: "false"
  runs: 5

# SolO data configuration (if using SolO dataset)
SolO_data:
  solo_img_dir: "/mnt/data/ML-Ready_clean/SolO/SolO/ML-Ready-SolO"
  sxr_dir: "${base_data_dir}/SXR"
  sxr_norm_path: "${base_data_dir}/SolO/SXR/normalized_sxr.npy"

# Stereo data configuration (if using Stereo dataset)
Stereo_data:
  stereo_img_dir: "/mnt/data/ML-Ready-mixed/STEREO_processed"
  sxr_dir: "/mnt/data/ML-Ready-mixed/ML-Ready-mixed/SXR"
  sxr_norm_path: "/mnt/data/ML-READY/SXR/normalized_sxr.npy"

# Model parameters
model_params:
  input_size: 512
  patch_size: 16
  batch_size: 16
  no_weights: false  # Set to true to skip saving attention weights

# Model architecture parameters (should match training config)
vit_custom:
  embed_dim: 512
  num_channels: 6
  num_classes: 1
  patch_size: 16
  num_patches: 1024
  hidden_dim: 512
  num_heads: 8
  num_layers: 6
  dropout: 0.1

# Data paths
data:
  aia_dir: "${base_data_dir}/AIA-SPLIT/"
  sxr_dir: "${base_data_dir}/SXR-SPLIT/"
  sxr_norm_path: "${base_data_dir}/SXR-SPLIT/normalized_sxr.npy"
  checkpoint_path: "PLACEHOLDER_CHECKPOINT_PATH"  # Will be replaced by batch script

