
#Base directories - change these to switch datasets
base_data_dir: "/mnt/data/PAPER_DATA_B"  # Change this line for different datasets
base_checkpoint_dir: "/mnt/data/PAPER_DATA_B"    # Change this line for different datasets
wavelengths: [94, 131, 171, 193, 211, 304, 335]  # AIA wavelengths in Angstroms

# GPU configuration
# Options:
#   - Single GPU: gpu_ids: 0  or  gpu_ids: [0]
#   - Multi GPU: gpu_ids: [0, 1]  (uses both GPU 0 and 1)
#   - All GPUs: gpu_ids: "all"  (uses all available GPUs)
#   - CPU only: gpu_ids: -1
gpu_ids: "all"  # Use both GPUs
# Model configuration
selected_model: "ViTLocal"  # Options: "hybrid", "vit", "fusion", "vitpatch"
batch_size:    4
epochs:        250
oversample: false
balance_strategy: "upsample_minority"
calculate_base_weights: false  # Whether to calculate class-based weights for loss function

vit_custom:
    embed_dim: 256
    num_channels: 7
    num_classes: 1
    patch_size: 8
    num_patches: 4096
    hidden_dim: 512
    num_heads: 8
    num_layers: 6
    dropout: 0.1
    lr: 0.0001


# Data paths (automatically constructed from base directories)
data:
  aia_dir:
    "${base_data_dir}/AIA"
  sxr_dir:
    "${base_data_dir}/SXR"
  sxr_norm_path:
    "${base_data_dir}/SXR/normalized_sxr.npy"
  checkpoints_dir:
    "${base_checkpoint_dir}/new-checkpoint/"

wandb:
  entity: jayantbiradar619-university-of-arizona # Use your exact W&B username
  project: Paper
  job_type: training
  tags:
    - aia
    - sxr
    - regression
  wb_name: paper-testing-8-patch-335-512-hidden-6-layers-256-embed-dim
  notes: Regression from AIA images (6 channels) to GOES SXR flux