
#Base directories - change these to switch datasets
base_data_dir: "/mnt/data/NO-OVERLAP"  # Change this line for different datasets
base_checkpoint_dir: "/mnt/data/NO-OVERLAP"    # Change this line for different datasets
wavelengths: [94, 131, 171, 193, 211, 304]  # AIA wavelengths in Angstroms

# GPU configuration
gpu_id: 0  # GPU device ID to use (0, 1, 2, etc.) or -1 for CPU only
# Model configuration
selected_model: "ViTLocal"  # Options: "hybrid", "vit", "fusion", "vitpatch"
batch_size:    128
epochs:        250
oversample: false
balance_strategy: "upsample_minority"
calculate_base_weights: false  # Whether to calculate class-based weights for loss function

vit_custom:
    embed_dim: 512
    num_channels: 6
    num_classes: 1
    patch_size: 16
    num_patches: 1024
    hidden_dim: 512
    num_heads: 8
    num_layers: 6
    dropout: 0.1
    lr: 0.0001


# Data paths (automatically constructed from base directories)
data:
  aia_dir:
    "${base_data_dir}/AIA"
  sxr_dir:
    "${base_data_dir}/SXR"
  sxr_norm_path:
    "${base_data_dir}/SXR/normalized_sxr.npy"
  checkpoints_dir:
    "${base_checkpoint_dir}/new-checkpoint/"

wandb:
  entity: jayantbiradar619-university-of-arizona # Use your exact W&B username
  project: Model Testing
  job_type: training
  tags:
    - aia
    - sxr
    - regression
  wb_name: vit-local-patch
  notes: Regression from AIA images (6 channels) to GOES SXR flux